### ISSUE TITLE
Use prebuild instead of node-pre-gyp?

### ISSUE THREAD

**Issue by vweevers** [mcollina/native-hdr-histogram#19]
@mcollina I was looking at the current build setup and oof, I'm not too eager to dive into that. I think it'd be worthwhile to try starting from scratch, using `prebuild` + `prebuild-install` + `prebuild-ci`, and storing release assets on GitHub. If that doesn't pan out I'll stick to the current setup.

Any strong feelings about this?

**Comment by mcollina** [comment]
go for it!

**Comment by mcollina** [comment]
This would be fantastic to do @jschlight, so we can include the prebuilt bundles in the package itself.

**Comment by jschlight** [comment]
I agree. I've put it on my list.

**Comment by jschlight** [comment]
Just a quick note that I'm now able to publish GitHub Releases using `prebuild`:

https://github.com/jschlight/native-hdr-histogram/releases/tag/v0.8.0

The next step is to verify that `prebuild-install` is working for users.

And since I need to update the CI scripts anyway, I might as well take a crack at updating them to GitHub Actions. #37

**Comment by mcollina** [comment]
amazing!

**Comment by mcollina** [comment]
What should I do to publish a release then?

**Comment by vweevers** [comment]
> so we can include the prebuilt bundles in the package itself

@mcollina `prebuild` doesn't do that (it downloads assets from GH), did you mean to use `prebuildify` instead?

**Comment by mcollina** [comment]
Yes!

**Comment by jschlight** [comment]
I'll take a look at `prebuildify`. 😀

**Comment by jschlight** [comment]
A quick update. I've got this working with `prebuildify` on this branch:

https://github.com/jschlight/native-hdr-histogram/tree/jschlight/ch1237/add-prebuildify-support

The resulting npm package, which includes the following four binaries, is less than 1MB:

- darwin-x64
- linux-x64
- win32-ia32
- win32-x64

This branch is ready to be made into a PR. 

The only thing holding me back is that the builds are still done with TravisCI and AppVeyor. I'd like to see if I can get the builds to work with GitHub Actions and then inquire about contributing that code back to `prebuildify-ci`. 

What is the consensus here? Do you want a PR now based on TravisCI and AppVeyor? Or wait a bit longer for builds using GitHub Actions?

**Comment by jschlight** [comment]
I've got a GitHub workflow in the branch linked above that is compatible with `prebuilfify-ci` and successfully building all supported binaries. I expect to have a PR here in the next few days after I cleanup all the loose ends. This PR will:

- Bundle the binaries in the npm module downloaded by the user
- Eliminate the project's dependency on AWS S3
- Eliminate the project's dependencies on Travis CI and AppVeyor

**Comment by mcollina** [comment]
amazing!
