### ISSUE TITLE
Release semver-major

### ISSUE THREAD

**Issue by vweevers** [mcollina/native-hdr-histogram#22]
@mcollina Should the new version be 0.5.0 (because we're 0.x) or is it time to jump to 1.0.0?

And to make sure I got it right, the workflow is:

```
npm version minor -m "[publish binary] %s"
git push --follow-tags
# (wait for builds to complete)
npm publish
```

Correct?

**Comment by mcollina** [comment]
should be! Go for 0.5.0.
Il giorno mar 11 set 2018 alle 14:46 Vincent Weevers <
notifications@github.com> ha scritto:
