### ISSUE TITLE
Should Node 6 be supported?

### ISSUE THREAD

**Issue by ahwayakchih** [mcollina/native-hdr-histogram#25]
While working on #24 i noticed that `tap` 13.x dropped support for Node v6.
Should `native-hdr-histogram` drop it too, or should it stay with `tap` 12.x?

**Comment by mcollina** [comment]
let's drop node 6.

Il giorno mar 14 mag 2019 alle ore 12:46 Marcin Konicki <
notifications@github.com> ha scritto:

**Comment by ahwayakchih** [comment]
Thanks!

**Comment by ahwayakchih** [comment]
Since we dropped Node v6, should next version be `1.0.0`?

**Comment by vweevers** [comment]
Yes

**Comment by vweevers** [comment]
It could also be 0.6.0 but I think this module is stable enough for 1.0.0. WDYT @mcollina?

**Comment by mcollina** [comment]
Yes I agree.

**Comment by mcollina** [comment]
I think @thekemkid did 0.6.0. That's ok as well.
