### ISSUE TITLE
Version in NPM is at 0.5.0

### ISSUE THREAD

**Issue by ahwayakchih** [mcollina/native-hdr-histogram#31]
Any chance for an updated version in NPM :)?

When i open https://www.npmjs.com/package/native-hdr-histogram it shows version 0.5.0.
It would be great if i could get version 0.6.0 from npm.

**Comment by mcollina** [comment]
@thekemkid would you mind checking if we have the prebuilts in place and release?

**Comment by GlenTiki** [comment]
I missed this. will do now

**Comment by GlenTiki** [comment]
I'm trying `npm publish` with the published binaries at v0.6.0, but I seem to be missing npm perms

```
Glens-MacBook-Pro:native-hdr-histogram glen$ npm publish

...  snip ...

npm ERR! code E403
npm ERR! 403 Forbidden - PUT https://registry.npmjs.org/native-hdr-histogram - You do not have permission to publish "native-hdr-histogram". Are you logged in as the correct user?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/glen/.npm/_logs/2019-06-04T16_19_13_623Z-debug.log
```

`npm whoami` still shows my creds logged in.

Add me as a collaborator on npm or you run the following to cleanup current master.

Please checkout this commit and run `npm publish` locally:

```
git checkout v0.6.0 && npm publish && git checkout master
```

If you want the tag the _latest_ master for release:

```
npm i && npm version minor && git commit --amend -c "[publish binary] 0.7.0" && git push origin master && git push origin v0.7.0 && npm publish"
```

**Comment by vweevers** [comment]
```
$ npm owner ls native-hdr-histogram
matteo.collina <hello@matteocollina.com>
vweevers <dev@vincentweevers.nl>
```

I forgot I have publish rights here. @thekemkid what's your npm username? I'll add you

**Comment by mcollina** [comment]
I've just added @thekemkid!

**Comment by GlenTiki** [comment]
0.6.0 and 0.7.0 are available on npm. bins are building for 0.7.0

**Comment by ahwayakchih** [comment]
Thanks!
