### ISSUE TITLE
Support for hdr_add

### ISSUE THREAD

**Issue by ccollie** [mcollina/native-hdr-histogram#32]
Im using the `typescript` version to support rollups only because this lib seems not to support adding histograms (or any method of iteration for that matter).

Is it possible to add support for `hdr_add`. I'd be willing to provide a small bit of funding (my use-case is for an OSS project, not commercial)

**Comment by mcollina** [comment]
Thanks for offer, but I'd be happier to receive a PR that implement that feature.

What do you mean by `hdr_add`? Is this a feature of the hdr histogram that we are not exposing?

**Comment by ccollie** [comment]
Thanks for the response. It's been forever since I've touched `c/c++` but i'd be willing to dig in.
Basically i'm looking for the ability to add one histogram to another for aggregation purposes
(ex. if i'm sampling latencies at `1m` intervals and storing the data, i'd like to roll up to `1h`, `1d` etc on a schedule)

The `HdrHistogram_c` implements `hdr_add` which implements what i'm after.
